[package]
name = "lufact-sys"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Rust binding to lufact FORTRAN routines"
repository = "https://github.com/rwl/lufact-sys"

[dependencies]
libc = "0.2"